ProjectDaNyan/Assets/ProjectDaNyan/Prefab_NY/Floor.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefab_NY/OriginalFloor.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefab_NY/OriginalFloor.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefab_NY/boxCat.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/MapManager.cs
ProjectDaNyan/ProjectSettings/TagManager.asset

1. 새로운 맵 리소스에 코드 적용
- 새로운 맵 리소스에 MapManager 스크립트 적용
- boxCat 태그 생성 ➡️ boxCat 오브젝트에 추가
- boxCat 스폰 위치 y값 수정
- Player 오브젝트가 이동할 때마다 가라앉는 현상 발견 ➡️ Rigidbody 설정에서 y값 위치 Freeze

Improve: 새로운 맵 리소스에 코드 적용

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/BasicBullet.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/BasicBullet.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/BulletPostion.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/BulletPostion.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/Laser.mat
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/Laser.mat.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/Laser.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/Laser.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/UpgradedBullet.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/UpgradedBullet.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Bullet.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Bullet.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/EneymyScanner.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/EneymyScanner.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerAttack.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerAttack.cs.meta
ProjectDaNyan/ProjectSettings/ProjectSettings.asset

1. 기본, 초월, 관통 공격 구현
2. 가까운 적 추적 스크립트 추가

Add: 기본, 초월, 관통 공격 구현

---

ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_road.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_white.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/BulletPostion.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Kiyoung.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Kiyoung.unity.meta

Add: BulletPosition prefab 스크립트 적용

---

ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/Ground_Tile_01.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_road.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_road_edge.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_road_line.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_road_linecenter.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Models/Blocks/block_white.blend.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/ShelterScene_kihyun.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_kihyun.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_kihyun.unity.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/ShelterUI/ShelterUIScript.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

StageScene.unity :
- -------[UI], ------[Space], -------[Global] 의 좌표를 0,0,0으로 수정
- PauseCanvas -> PauseUI.prefab으로 변경
- 기존 에셋 StageUI 로 묶음
- StageClearUI 추가
- BulletPosition 프리펩 플레이어에 추가
- Floor 에셋 read/write 세팅
------
ShleterScene.unity :
- -------[UI], ------[Space], -------[Global] 의 좌표를 0,0,0으로 수정
-----
Prefab :
Camera Default 좌표값 수정
Floor.prefab에 mapfloor Array 할당

Fix: 최상위 게임오브젝트 좌표 0,0,0으로 수정, UI script 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/ControllerUI/JoystickController.cs
ProjectDaNyan/ProjectSettings/TagManager.asset

작업 내역:
- 대시해서 벽에 닿으면 이동방향 반사
- 대시해서 바위에 닿으면 바위 위로 올라감, 바위 위에서 대시하면 내려올 수 있음
고쳐야 할 부분:
- 벽 바로 앞에서 대시하면 드드득 거리면서 애매하게 벽에 끼임
> Raycast로 벽이 근처에 있으면 그쪽으로 이동 못하게 막던지 해야 하나? 도와주세요!!!
- 원래는 바위 위에서 대시하면 바위 아래로 내려오고 그 상태에서 대시를 해야 하는데
이렇게 하려니 코드 재사용성이 꼬여서 일단 포물선으로 점프해서 내려오게 제작함.
수정 필요.

Add: 벽에 대시로 닿으면 반사, 바위에 대시로 닿으면 올라가서 대시로 탈출 가능

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/Player.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Rubik.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내용 :
1. 플레이어 전면부 충돌 범위 증가 -> 특정 각도에서 벽이랑 미묘하게 충돌 판정이 발생하지 않는 문제 수정.
2. (1) 문제가 수정됨에 따라, (1) 문제를 수정하기 위해 시도했던 필요없는 코드 정리
3. 플레이어 오브젝트 프리팹화

Fix: 플레이어 충돌 범위, 필요없는 코드 제거, 플레이어 오브젝트 프리팹화

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageFailedUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageFailedUI.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageMainUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageUI.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_kihyun.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/SliderPlayerHP.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/SliderPlayerHP.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

변경과정 중 PlayerStatus 중 필요한 데이터 (플레이어 체력) get 함수 추가

Add: PlayerHP 표시UI 추가, StageFailedUI 프리펩 추가

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/MapManager.cs

작업 내용 :
- 맵 이동 시 네브메쉬 업데이트 방식 변경

Fix: 맵 이동 시 이동한 만큼만 네브메쉬가 만들어지도록 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

작업 내용:
- 적에게 최초로 닿을 시 즉시 1회 10의 데미지를 입음
- 0.1초에 한번씩 지금 닿아 있는 적 * 1의 데미지를 입음
- 적에게서 떨어지면 지금 닿아 있는 적이 줄어들음
> 근데 자꾸 적들이 원힛킬 나서 테스트를 제대로 못해봄... 좀더 자세한 테스트 필요
- boxCat은 이제 더 이상 적 판정을 가지지 않음
- 그냥 가서 먹으면 경험치가 오르고, 경험치가 일정 수준 이상 올라가면 레벨이 오름

Add: 피격 판정, 레벨업 판정 추가

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterBoss.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterElitePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterShortRangePrefab.prefab

Fix Monster collision trigger off

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/EXPBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/EXPBox.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterEliteLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterEliteShortRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Player_characrer_monster/MonsterShortRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/EXPBox.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/EXPBox.cs.meta

- EXP Box prefab 추가 하였습니다.
- 몬스터 사망 시 pop 합니다.

Add EXP Box when monster is dead

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/Floor.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/HiddenBox.mat
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/HiddenBox.mat.meta
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/HiddenBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/HiddenBox.prefab.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/GameManager.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/MapManager.cs

1. 히든 스킬 박스 드랍 코드 구현
- 33초(플레이 시간 / 2 + 준비시간) 뒤 랜덤한 위치에 hiddenBox 오브젝트 드랍
- SetHiddenBox(), DropHiddenBox() 함수 추가
2. HiddenBox 오브젝트 추가
- Material 생성 ➡️ 다른 오브젝트와 구분하기 위해
- 큐브 오브젝트에 + Material 추가

Add: 히든 스킬 박스 드랍 코드 구현

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/Camera.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_kihyun.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MonsterBoss.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MonsterManager.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/CameraManager.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/CameraManager.cs.meta

보스 출현 시 카메라가 보스를 2초 간 비추는 기능 추가
MonsterBoss 스크립트 OnEnable에 CameraFocusOnBoss 추가
MonsterManager 리포맷

Add: 보스 포커싱 기능 추가

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/0.Blend/New Animator Controller.controller
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/0.Blend/New Animator Controller.controller.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Materials/Player_cat 1.mat
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Materials/Player_cat 1.mat.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Materials/Player_cat 2.mat
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Materials/Player_cat 2.mat.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/PlayerAnimator.controller
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/PlayerAnimator.controller.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내용 :
- 플레이어 메쉬를 고양이로 변경
- 기존 큐브 메쉬는 삭제
- 고양이 메쉬에 메쉬 콜라이더 적용
- 충돌 이펙트 제대로 작동 확인함

Add: 플레이어 고양이 메쉬 추가

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/1.Monster/Monster_boss_.fbx.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/1.Monster/Monster_type_A.fbx.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/1.Monster/Monster_type_B.fbx.meta

Fix: 몬스터 오브젝트 Read/Write 추가

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/PlayerAnimator.controller
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

- 작업 내역 :
애니메이터 내 파일이 모두 날아가서 애니메이션이 나오지 않는 현상을 수정했습니다.
콜라이더가 사라져서 isTrigger이 켜져 있는 오브젝트를 제외한 나머지 오브젝트와 충돌이 되지 않는 현상을 수정했습니다.

Fix: 애니메이션 미출력 버그, 충돌 안되는 버그

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/PlayerData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/PlayerData.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

작업 내용:
- 기획단에서 수치 조절을 쉽게 할 수 있도록 PlayerData 스크립터블 오브젝트 적용

Add: PlayerData 스크립터블 오브젝트

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/EXPBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/boxCat.prefab
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MagnetData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MagnetData.asset.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MagnetData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MagnetData.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Magnet.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Magnet.cs.meta

작업내역:
- boxCat, ExpBox 위치가 플레이어와 적당히 가까워지면 자석으로 끌려가게 만듦
- 스크립터블 오브젝트로 기획단에서 아이템이 끌려가는 속도랑, 자석 범위 조절 가능

Add: 자석 시스템

---

ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/PlayerData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/ControllerUI/Base/JoystickController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/ControllerUI/Editor/JoystickControllerEditor.cs

- 작업 내역
대시 횟수를 제한합니다.
대시 횟수는 2회까지 충전 가능합니다.
일정 시간이 지나면대시 횟수가 충전됩니다.
바위 위에 올라가있는 상태에서는 횟수 차감 없이 대시가 가능합니다

Add: 대시 횟수 제한

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/PlayerData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

- 작업 내용
바위에 올라가고 1초가 지나면 강제 사출
사출 방향 : 아무 입력 없을 시 캐릭터가 바라보고 있는 방향
수치 변경 가능하도록 스크립터블오브젝트에 사출 시간 정해둠

Add: 바위에 올라가고 일정 시간이 지나면 강제 사출

---

ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity

StageScene.unity 에서 사용하지 않는 프로퍼티 삭제

Fix: 사용하지 않는 프로퍼티 삭제

---

ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_01.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_02.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_03.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_04.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_05.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_06.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_07.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_08.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_09.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_10.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_11.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_12.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_13.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_14.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_15.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapElement_16.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Maps/Prefebs/MapFloor.prefab
ProjectDaNyan/ProjectSettings/TagManager.asset

1. Map_Floor 레이어 추가
- 드론 공격 구현을 위해 MapFloor에 레이어 추가
- Map_Floor 레이어 생성
- MapFloor에 Map_Floor 적용

Add: MapFloor에 Map_Floor 레이어 추가

---

.githooks/pre-push

실행권한을 추가하였습니다.
`git add --chmod=+x .githooks/*`

Fix: 깃훅 규칙 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/ItemController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/MapManager.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

1. 아이템 드랍 로직 수정
- 고양이/골드/에너지 드랍 변수 개별화
2. 자석 드랍 추가
- 10% 확률로 몬스터 경험치 흡인용 자석 드랍

Improve: 아이템 드랍 로직 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내역 :
- 걷기 시 짧은 길이의 이동방향 표시 (짧은 길이 = 임의로 지정)
- 대시 가능할 때 대시로 이동 가능한 만큼의 이동방향 표시
- 바위 위에서도 작동함

Improve: 대시 비주얼 향상

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Player_Physics.physicMaterial
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Player_Physics.physicMaterial.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Rubik.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Rubik.unity.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내역:
1. OnControllerColliderHit을 사용해 캐릭터 컨트롤러 기반의 충돌 감지 시스템으로 변경
2. 이를 통해 벽 가까이에서 대시했을 때 안 튕기거나 캐릭터가 마찰로 인해 끼이는 현상 수정
3. 벽이나 바위가 아닌 물체에 대시하면 충돌 시 대시 끊김

Improve: 충돌 판정 섬세화 및 벽 가까이에서 대시할 경우 대시 안되는 현상 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterBossA.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/MonsterAttackPrefabs/Blast.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/MonsterAttackPrefabs/MonsterNormalBullet.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Santa.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Santa.unity.meta
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/GameManagerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterBossA.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterFatMan.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterSkillWaveBlast.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MonsterManager.cs

- 보스 A 기본 공격 수정
- 보스 A 대쉬 후 충격파 & 전체 충격파 콜라이더 수정
- 보스몹이 총에 맞을때 떨리는 현상 수정
- 일반 몬스터 피격 효과 수정

Improve: boss monster A logic

---

ProjectDaNyan/Assets/Apple.Core.meta
ProjectDaNyan/Assets/Apple.Core/Editor.meta
ProjectDaNyan/Assets/Apple.Core/Editor/DefaultAppleBuildProfile.asset
ProjectDaNyan/Assets/Apple.Core/Editor/DefaultAppleBuildProfile.asset.meta
ProjectDaNyan/Packages/manifest.json
ProjectDaNyan/Packages/packages-lock.json

작업 내용:
애플 패키지 문제로 빌드 에러
당장 해결 불가능 - 일단 빌드 가능하도록 제거

Fix:애플 패키지 문제로 빌드 불가능

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterBossA.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/MonsterAttackPrefabs/Blast.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/Camera.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Santa.unity
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterBossAData.asset

- 보스 A의 충격파 라인 랜더러가 보이지 않는 현상 수정
- 카메라 curling mask 수정

Improve : Boss A Blast Attack Line Renderer

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerDroneAttack.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/SkillSelectUI.cs

1. 레벨업 후 ui에서 레벨업할 스킬 선택 가능
2. 일단 기본공격, 드론공격, 폭탄공격 세개 선택 가능

Add: 레벨업하면 스킬 선택해서 레벨업 구현

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/0.Player_cat/1.Materials/Materials/Movement_direction.mat
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내역:
플레이어 대시 공격이 대시 중에만 작동되도록 수정
바위대시, 벽대시 모두 가능

Improve: 플레이어 대시 공격 활성화/비활성화 시스템 개선

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

작업 내역:
PlayerStatus에 있는 Player_Level 변수가 레벨업되지 않는 현상 발견,
로직 추가로 문제 해결

Add: PlayerStatus에서 레벨업 로직 추가

---

ProjectDaNyan/ProjectSettings/ProjectSettings.asset

Alt+Tab 소프트로 빌드앤런 되도록 설정
이전에 빌드해본적이 없는 아이폰의 경우, xcode에서 register device를 해야 등록이 되는 점 참고바랍니다.

Improve: 프로젝트 세팅값 조정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/PauseUI.cs

작업 사항
- Skill Element의 Out of index 카운트에 대한 예외 처리

Fix: 일시정지 메뉴가 게임을 완전정지 하는 문제 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/EXPBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/boxCat.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MagnetData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/ItemController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Magnet.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/PlayInfo/CollectedBoxCatText.cs
ProjectDaNyan/ProjectSettings/TagManager.asset

1. 아이템 드랍 관련 오류 해결
2. 아이템 동작 개선
- 에너지 회복 기능 추가
- 자석 기능 추가

Improve: 아이템 동작 개선

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/EXPBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Materials/Exp_Green.mat
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Materials/Exp_Green.mat.meta
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/boxCat.prefab

작업 내역 :
박스캣 다지안 기존 플레이어 고양이 모델링 재활용해서 제작
EXPbox 디자인이 이상한 보라색 상자가 나와서 초록색으로 변경

improve: boxcat, expbox 디자인 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

- 레이저 프리펩 오버라이딩
- EXPBox 용 태그 처리 임시로 처리 (임시)

Fix: EXPbox

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerController.cs

작업 내역:
보스전 벽 세워지는 동안 PlayerStop() 함수 실행

Fix: 보스전 시작 시 캐릭터 안 움직이게

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/SkillSelectUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageFailedUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

- Failed UI에서 이상 동작하는 ScriptUI 삭제,
- Camera 컬링 마스크 추가
- 게임 실패, 성공 시 다시시작 기능 활성화

Improve: UI 관련 게임 멈추는 버그 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/PlayerAttackPosition.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

1. 플레이어 레벨 표시 수정
- 레벨 1로 고정 ➡️ 스킬업 할 때마다 레벨업 하도록 수정
2. 드론 공격 시작 레벨 수정
- 4에서 1로 수정

Fix: 레벨업 표시 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

Fix : item drop

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerStatus.cs

Fix : EXP Box 경험치 획득 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab

Fix: 플레이어 충돌 범위 증가

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/ShelterPrefab/ShelterUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity

Fix: TempUI 관련 오류 해결

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/SkillBoxes/SkillInfoUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/SkillSelectUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageMainUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/PlayerData.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/ItemController.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/PlayerLevelSlider.cs

Fix: PlayerEXPSlider 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageClearUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageFailedUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageClearUI.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageClearUI.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageFailedUI.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageFailedUI.cs.meta
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

Fix: 무한 일시정지 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/EXPBox.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterEliteLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterEliteShortRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterShortRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/EXPBox.cs

Fix : EXP Box IsTrigger checked

---

ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterEliteLongRange.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterEliteShorRange.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterManagerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterNormalLongRage.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterNormalShortage.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset

작업 내역:
조이가 작업하신 밸런스 조정값을 적용합니다.

improve: 밸런스 조정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterEliteLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterEliteShortRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/MonsterLongRangePrefab.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene_Santa.unity
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/GameManagerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterBossBData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterEliteLongRange.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterEliteShorRange.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterManagerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/MonsterNormalShortage.asset
ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/PlayerData.asset
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/GameObjectPool.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/Monster.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterBossB.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterFatMan.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/MonsterManager.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/ObjectPoolManager.cs

- Boss B Fatman 벽에 닿을 떄 생기는 오류 수정
- Boss 피격 시 색상 변하지 않는 오류 수정
- ObjectPool 오류 수정
- 약간의 밸런스 조절

Improve : game balance and bug fix

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/StageUIScript.cs

Fix: 게임 시작 시 레이저 하나 줌

---

ProjectDaNyan/Assets/ProjectDaNyan/ScriptableObject/GameManagerData.asset

Fix: 게임 시작 시간 180초

---

ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/Space/AttackPrefab/Bomb/BombBullet.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/Monster.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Global/Monster/MonsterNormal.cs
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/Bullet.cs

1. 보스 폭탄 재부착할 때 머리 위에 표식 안되는 경우 수정
2. 보스한테 부착된 폭탄이 너무 낮게 생성되던거 수정

Fix: 보스 폭탄 부착 버그 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/Space/PlayerAttack.cs

Fix: 드론 레벨업 버그 수정

---

ProjectDaNyan/Assets/ProjectDaNyan/Player_characrer_monster/Player.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Prefabs/UI/StagePrefab/StageUI.prefab
ProjectDaNyan/Assets/ProjectDaNyan/Scenes/StageScene.unity
ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/PlayerExpSlider.cs

Fix: 캐릭터 체력바 드드득 현상

---

ProjectDaNyan/Assets/ProjectDaNyan/Scripts/UI/StageUI/SkillSelectUI.cs

Improve: delete overlapped exp
